/**
 * Copyright 2026 GoodRx, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** Reviewed target auth policy for every exported /api/v2 method; enforced against the route tree by v2RoutePolicyManifest.test.ts. */

export type V2HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type V2KeyScope = 'env:read' | 'env:write' | 'sites:read' | 'sites:write' | 'repos:read' | 'repos:write';

export type V2RoutePolicyEntry =
  | { method: V2HttpMethod; route: string; policy: 'public' }
  | { method: V2HttpMethod; route: string; policy: 'session'; roles?: readonly ['admin'] }
  /* scope null = any authenticated principal, reserved for pure functions with no data access */
  | { method: V2HttpMethod; route: string; policy: 'principal'; scope: V2KeyScope | null };

export const V2_ROUTE_POLICY_MANIFEST: readonly V2RoutePolicyEntry[] = [
  { method: 'GET', route: '/api/v2/ai/admin/agent/capabilities', policy: 'session', roles: ['admin'] },
  { method: 'PUT', route: '/api/v2/ai/admin/agent/capabilities', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/admin/agent/creation-policy', policy: 'session', roles: ['admin'] },
  { method: 'PUT', route: '/api/v2/ai/admin/agent/creation-policy', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/admin/agent/instruction-rules', policy: 'session', roles: ['admin'] },
  { method: 'PUT', route: '/api/v2/ai/admin/agent/instruction-rules', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/admin/agent/instruction-templates', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/admin/agent/instruction-templates/{ref}', policy: 'session', roles: ['admin'] },
  {
    method: 'PUT',
    route: '/api/v2/ai/admin/agent/instruction-templates/{ref}/override',
    policy: 'session',
    roles: ['admin'],
  },
  {
    method: 'POST',
    route: '/api/v2/ai/admin/agent/instruction-templates/{ref}/reset',
    policy: 'session',
    roles: ['admin'],
  },
  { method: 'GET', route: '/api/v2/ai/admin/agent/mcp-servers', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/admin/agent/mcp-servers/{slug}/users', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/admin/agent/prompt-preview', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/admin/agent/sandbox-pools', policy: 'session', roles: ['admin'] },
  {
    method: 'GET',
    route: '/api/v2/ai/admin/agent/sandbox-pools/{namespace}/{name}',
    policy: 'session',
    roles: ['admin'],
  },
  {
    method: 'PATCH',
    route: '/api/v2/ai/admin/agent/sandbox-pools/{namespace}/{name}',
    policy: 'session',
    roles: ['admin'],
  },
  { method: 'GET', route: '/api/v2/ai/admin/agent/sessions', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/admin/agent/sessions/{sessionId}', policy: 'session', roles: ['admin'] },
  {
    method: 'GET',
    route: '/api/v2/ai/admin/agent/threads/{threadId}/conversation',
    policy: 'session',
    roles: ['admin'],
  },
  { method: 'GET', route: '/api/v2/ai/admin/agent/tools', policy: 'session', roles: ['admin'] },
  { method: 'DELETE', route: '/api/v2/ai/agent/api-keys', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/api-keys', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/api-keys', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/build-context-chats', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/definition-capabilities', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/definitions', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/definitions', policy: 'session' },
  { method: 'DELETE', route: '/api/v2/ai/agent/definitions/{definitionId}', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/definitions/{definitionId}', policy: 'session' },
  { method: 'PATCH', route: '/api/v2/ai/agent/definitions/{definitionId}', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/github-token', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/mcp-connections', policy: 'session' },
  { method: 'DELETE', route: '/api/v2/ai/agent/mcp-connections/{slug}', policy: 'session' },
  { method: 'PUT', route: '/api/v2/ai/agent/mcp-connections/{slug}', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/mcp-connections/{slug}/oauth/callback', policy: 'public' },
  { method: 'POST', route: '/api/v2/ai/agent/mcp-connections/{slug}/oauth/start', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/models', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/pending-actions/{actionId}/respond', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/preview-grants', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/runs/{runId}', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/runs/{runId}/cancel', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/runs/{runId}/events', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/runs/{runId}/events/stream', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/runtime-config', policy: 'session' },
  { method: 'PATCH', route: '/api/v2/ai/agent/runtime-config', policy: 'session', roles: ['admin'] },
  { method: 'PUT', route: '/api/v2/ai/agent/runtime-config', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/agent/runtime-config/repos', policy: 'session' },
  { method: 'DELETE', route: '/api/v2/ai/agent/runtime-config/repos/{fullName+}', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/agent/runtime-config/repos/{fullName+}', policy: 'session' },
  { method: 'PUT', route: '/api/v2/ai/agent/runtime-config/repos/{fullName+}', policy: 'session', roles: ['admin'] },
  { method: 'POST', route: '/api/v2/ai/agent/runtime-controls/preview', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/sandbox-sessions', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/sandbox-sessions', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/sandbox-sessions/launches/{launchId}', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/session-candidates', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/sessions', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/sessions', policy: 'session' },
  { method: 'DELETE', route: '/api/v2/ai/agent/sessions/{sessionId}', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/sessions/{sessionId}', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/sessions/{sessionId}/sandbox/resume', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/sessions/{sessionId}/sandbox/suspend', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/sessions/{sessionId}/services', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/sessions/{sessionId}/threads', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/sessions/{sessionId}/threads', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/sessions/{sessionId}/unarchive', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/sessions/{sessionId}/workspace/keep', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/sessions/{sessionId}/workspace/open', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/sessions/{sessionId}/workspace/release', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/settings', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/threads/{threadId}', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/threads/{threadId}/agent', policy: 'session' },
  { method: 'PATCH', route: '/api/v2/ai/agent/threads/{threadId}/agent', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/threads/{threadId}/messages', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/threads/{threadId}/pending-actions', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/agent/threads/{threadId}/runs', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/threads/{threadId}/runtime-controls', policy: 'session' },
  { method: 'PATCH', route: '/api/v2/ai/agent/threads/{threadId}/runtime-controls', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/threads/{threadId}/tool-approval-allowlist', policy: 'session' },
  { method: 'PUT', route: '/api/v2/ai/agent/threads/{threadId}/tool-approval-allowlist', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/agent/threads/{threadId}/usage', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/config', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/config/agent-session', policy: 'session' },
  { method: 'PUT', route: '/api/v2/ai/config/agent-session', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/config/agent-session/effective', policy: 'session' },
  { method: 'DELETE', route: '/api/v2/ai/config/agent-session/repos/{fullName+}', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/config/agent-session/repos/{fullName+}', policy: 'session' },
  { method: 'PUT', route: '/api/v2/ai/config/agent-session/repos/{fullName+}', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/config/agent-session/runtime', policy: 'session', roles: ['admin'] },
  { method: 'PUT', route: '/api/v2/ai/config/agent-session/runtime', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/config/mcp-presets', policy: 'session' },
  { method: 'GET', route: '/api/v2/ai/config/mcp-servers', policy: 'session' },
  { method: 'POST', route: '/api/v2/ai/config/mcp-servers', policy: 'session', roles: ['admin'] },
  { method: 'DELETE', route: '/api/v2/ai/config/mcp-servers/{slug}', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/config/mcp-servers/{slug}', policy: 'session' },
  { method: 'PUT', route: '/api/v2/ai/config/mcp-servers/{slug}', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/ai/workspace-runtime/backends', policy: 'session', roles: ['admin'] },
  {
    method: 'POST',
    route: '/api/v2/ai/workspace-runtime/backends/{id}/deep-check',
    policy: 'session',
    roles: ['admin'],
  },
  {
    method: 'POST',
    route: '/api/v2/ai/workspace-runtime/backends/{id}/template-build',
    policy: 'session',
    roles: ['admin'],
  },
  {
    method: 'GET',
    route: '/api/v2/ai/workspace-runtime/backends/{id}/template-build/{buildId}',
    policy: 'session',
    roles: ['admin'],
  },
  {
    method: 'POST',
    route: '/api/v2/ai/workspace-runtime/backends/{id}/test-connection',
    policy: 'session',
    roles: ['admin'],
  },
  {
    method: 'GET',
    route: '/api/v2/ai/workspace-runtime/backends/{id}/workspace-sources',
    policy: 'session',
    roles: ['admin'],
  },
  { method: 'GET', route: '/api/v2/auth/context', policy: 'principal', scope: null },
  { method: 'GET', route: '/api/v2/builds', policy: 'principal', scope: 'env:read' },
  { method: 'GET', route: '/api/v2/builds/{uuid}', policy: 'principal', scope: 'env:read' },
  { method: 'PATCH', route: '/api/v2/builds/{uuid}', policy: 'principal', scope: 'env:write' },
  { method: 'PUT', route: '/api/v2/builds/{uuid}/destroy', policy: 'principal', scope: 'env:write' },
  { method: 'GET', route: '/api/v2/builds/{uuid}/metadata', policy: 'principal', scope: 'env:read' },
  { method: 'GET', route: '/api/v2/builds/{uuid}/pods', policy: 'principal', scope: 'env:read' },
  { method: 'PUT', route: '/api/v2/builds/{uuid}/redeploy', policy: 'principal', scope: 'env:write' },
  { method: 'PATCH', route: '/api/v2/builds/{uuid}/services', policy: 'principal', scope: 'env:write' },
  { method: 'GET', route: '/api/v2/builds/{uuid}/services/{name}/build-jobs', policy: 'principal', scope: 'env:read' },
  {
    method: 'GET',
    route: '/api/v2/builds/{uuid}/services/{name}/build-jobs/{jobName}',
    policy: 'principal',
    scope: 'env:read',
  },
  { method: 'GET', route: '/api/v2/builds/{uuid}/services/{name}/deploy-jobs', policy: 'principal', scope: 'env:read' },
  {
    method: 'GET',
    route: '/api/v2/builds/{uuid}/services/{name}/deploy-jobs/{jobName}',
    policy: 'principal',
    scope: 'env:read',
  },
  { method: 'PUT', route: '/api/v2/builds/{uuid}/services/{name}/destroy', policy: 'principal', scope: 'env:write' },
  { method: 'GET', route: '/api/v2/builds/{uuid}/services/{name}/pods', policy: 'principal', scope: 'env:read' },
  { method: 'PUT', route: '/api/v2/builds/{uuid}/services/{name}/redeploy', policy: 'principal', scope: 'env:write' },
  { method: 'GET', route: '/api/v2/builds/{uuid}/webhooks', policy: 'principal', scope: 'env:read' },
  { method: 'PUT', route: '/api/v2/builds/{uuid}/webhooks', policy: 'principal', scope: 'env:write' },
  { method: 'GET', route: '/api/v2/config/api-environments', policy: 'session', roles: ['admin'] },
  { method: 'PUT', route: '/api/v2/config/api-environments', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/config/api-keys', policy: 'session', roles: ['admin'] },
  { method: 'PUT', route: '/api/v2/config/api-keys', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/config/metadata', policy: 'session', roles: ['admin'] },
  { method: 'POST', route: '/api/v2/config/metadata', policy: 'session', roles: ['admin'] },
  { method: 'DELETE', route: '/api/v2/config/metadata/{id}', policy: 'session', roles: ['admin'] },
  { method: 'PATCH', route: '/api/v2/config/metadata/{id}', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/config/sites', policy: 'session', roles: ['admin'] },
  { method: 'PUT', route: '/api/v2/config/sites', policy: 'session', roles: ['admin'] },
  { method: 'GET', route: '/api/v2/environments', policy: 'principal', scope: 'env:read' },
  { method: 'POST', route: '/api/v2/environments', policy: 'principal', scope: 'env:write' },
  { method: 'DELETE', route: '/api/v2/environments/{uuid}', policy: 'principal', scope: 'env:write' },
  { method: 'GET', route: '/api/v2/environments/{uuid}', policy: 'principal', scope: 'env:read' },
  { method: 'PATCH', route: '/api/v2/environments/{uuid}', policy: 'principal', scope: 'env:write' },
  { method: 'POST', route: '/api/v2/environments/{uuid}/deploy', policy: 'principal', scope: 'env:write' },
  { method: 'POST', route: '/api/v2/environments/{uuid}/extend', policy: 'principal', scope: 'env:write' },
  { method: 'GET', route: '/api/v2/environments/branches', policy: 'principal', scope: 'env:read' },
  { method: 'GET', route: '/api/v2/environments/config-preview', policy: 'principal', scope: 'env:read' },
  { method: 'GET', route: '/api/v2/environments/policy', policy: 'session' },
  { method: 'GET', route: '/api/v2/me/tokens', policy: 'session' },
  { method: 'POST', route: '/api/v2/me/tokens', policy: 'session' },
  { method: 'DELETE', route: '/api/v2/me/tokens/{id}', policy: 'session' },
  { method: 'GET', route: '/api/v2/me/tokens/policy', policy: 'session' },
  { method: 'GET', route: '/api/v2/repositories', policy: 'principal', scope: 'repos:read' },
  { method: 'POST', route: '/api/v2/repositories', policy: 'principal', scope: 'repos:write' },
  { method: 'DELETE', route: '/api/v2/repositories/{fullName+}', policy: 'principal', scope: 'repos:write' },
  { method: 'GET', route: '/api/v2/schema/validate', policy: 'principal', scope: 'repos:read' },
  { method: 'GET', route: '/api/v2/sites', policy: 'principal', scope: 'sites:read' },
  { method: 'POST', route: '/api/v2/sites', policy: 'principal', scope: 'sites:write' },
  { method: 'DELETE', route: '/api/v2/sites/{siteId}', policy: 'principal', scope: 'sites:write' },
  { method: 'GET', route: '/api/v2/sites/{siteId}', policy: 'principal', scope: 'sites:read' },
  { method: 'PUT', route: '/api/v2/sites/{siteId}/content', policy: 'principal', scope: 'sites:write' },
  { method: 'POST', route: '/api/v2/sites/{siteId}/extend', policy: 'principal', scope: 'sites:write' },
  { method: 'POST', route: '/api/v2/telemetry/events', policy: 'session' },
  { method: 'GET', route: '/api/v2/telemetry/stats', policy: 'session' },
  { method: 'GET', route: '/api/v2/tokens', policy: 'session', roles: ['admin'] },
  { method: 'POST', route: '/api/v2/tokens', policy: 'session', roles: ['admin'] },
  { method: 'DELETE', route: '/api/v2/tokens/{id}', policy: 'session', roles: ['admin'] },
  { method: 'POST', route: '/api/v2/tokens/revoke-all-user-tokens', policy: 'session', roles: ['admin'] },
  { method: 'POST', route: '/api/v2/tokens/revoke-by-owner', policy: 'session', roles: ['admin'] },
];
